name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker-cog-flux-schnell:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Install nix
      uses: cachix/install-nix-action@v27
    - name: Build image
      uses: nicknovitski/nix-develop@v1.1.0
      with:
        arguments: --command cog build -t cog-flux-schnell
    - name: Push docker image
      run: |
        docker tag cog-flux-schnell ghcr.io/nicolaschan/cog-flux-schnell:${GITHUB_REF#refs/*/}-${{ github.run_id }}
        docker tag cog-flux-schnell ghcr.io/nicolaschan/cog-flux-schnell:latest
        docker push ghcr.io/nicolaschan/cog-flux-schnell:${GITHUB_REF#refs/*/}-${{ github.run_id }}
        docker push ghcr.io/nicolaschan/cog-flux-schnell:latest
